name: resaurant_ui
version: 1.0.0+1


publish_to: none

description: A new Flutter project.

environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: 4.6.1
  get_it: ^7.2.0
  like_button: ^2.0.4
  animate_do: ^2.1.0

dev_dependencies: 
  build_runner: any
  flutter_gen_runner: any
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/fonts/
    - assets/colors/
  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica-Bold.ttf
        - asset: assets/fonts/Helvetica-light.ttf
          weight: 500

  uses-material-design: true

flutter_gen: 
  colors: 
    inputs: 
      - assets/colors/color.xml

